title: Technical Docs
description: Technical documentation for the Voxable API & CLI.
themeConfig:
  logo: '/logo.png'
  nav:
    - text: 'Voxable Homepage'
      link: 'https://voxable.io'
    - text: 'Voxable App'
      link: 'https://voxable.design'
    - text: 'Support'
      link: 'http://help.voxable.io'
  repo: 'voxable/cli'
  docsDir: docs
  editLinks: true
  sidebar:
    - title: 'ğŸ—ºï¸ Introduction'
      path: /
    - title: 'ğŸ–¥ï¸ The Voxable CLI'
      path: /cli/
    - title: 'ğŸ—ï¸ The Voxable API'
      path: /api/
    - title: 'âš™ï¸ CLI Plugins'
      path: /plugins/
      collapsable: false
      children:
        - title: Available Plugins
          path: /plugins/
        - title: Bespoken Plugin
          path: /plugins/bespoken
        - title: Colang Plugin
          path: /plugins/colang
    - title: 'ğŸ’» Contributing'
      collapsable: false
      path: /contributing/
      children:
        - title: Introduction
          path: /contributing/
        - title: Community
          path: /contributing/community
